// AUTO-GENERATED by scripts/generate-bible-data.mjs (app repo) — do not edit by hand.
//
// One `require` per book, behind a function, so a bundler inlines the JSON but
// nothing is parsed until a chapter is actually asked for. Both readers of the
// corpus go through here: the app (`data/bible-content.ts`) and the deployed
// conversation route (`bible-tools.ts`, via the loader the route passes in).

const bookLoaders: Record<string, () => string[][]> = {
  'gn': () => require('../corpus/gn.json') as string[][],
  'ex': () => require('../corpus/ex.json') as string[][],
  'lv': () => require('../corpus/lv.json') as string[][],
  'nm': () => require('../corpus/nm.json') as string[][],
  'dt': () => require('../corpus/dt.json') as string[][],
  'js': () => require('../corpus/js.json') as string[][],
  'jz': () => require('../corpus/jz.json') as string[][],
  'rt': () => require('../corpus/rt.json') as string[][],
  '1sm': () => require('../corpus/1sm.json') as string[][],
  '2sm': () => require('../corpus/2sm.json') as string[][],
  '1rs': () => require('../corpus/1rs.json') as string[][],
  '2rs': () => require('../corpus/2rs.json') as string[][],
  '1cr': () => require('../corpus/1cr.json') as string[][],
  '2cr': () => require('../corpus/2cr.json') as string[][],
  'esd': () => require('../corpus/esd.json') as string[][],
  'ne': () => require('../corpus/ne.json') as string[][],
  'tb': () => require('../corpus/tb.json') as string[][],
  'jdt': () => require('../corpus/jdt.json') as string[][],
  'et': () => require('../corpus/et.json') as string[][],
  'job': () => require('../corpus/job.json') as string[][],
  'sl': () => require('../corpus/sl.json') as string[][],
  'pr': () => require('../corpus/pr.json') as string[][],
  'ec': () => require('../corpus/ec.json') as string[][],
  'ct': () => require('../corpus/ct.json') as string[][],
  'sb': () => require('../corpus/sb.json') as string[][],
  'eclo': () => require('../corpus/eclo.json') as string[][],
  'is': () => require('../corpus/is.json') as string[][],
  'jr': () => require('../corpus/jr.json') as string[][],
  'lm': () => require('../corpus/lm.json') as string[][],
  'br': () => require('../corpus/br.json') as string[][],
  'ez': () => require('../corpus/ez.json') as string[][],
  'dn': () => require('../corpus/dn.json') as string[][],
  'os': () => require('../corpus/os.json') as string[][],
  'jl': () => require('../corpus/jl.json') as string[][],
  'am': () => require('../corpus/am.json') as string[][],
  'ab': () => require('../corpus/ab.json') as string[][],
  'jn': () => require('../corpus/jn.json') as string[][],
  'mq': () => require('../corpus/mq.json') as string[][],
  'na': () => require('../corpus/na.json') as string[][],
  'hc': () => require('../corpus/hc.json') as string[][],
  'sf': () => require('../corpus/sf.json') as string[][],
  'ag': () => require('../corpus/ag.json') as string[][],
  'zc': () => require('../corpus/zc.json') as string[][],
  'ml': () => require('../corpus/ml.json') as string[][],
  '1mc': () => require('../corpus/1mc.json') as string[][],
  '2mc': () => require('../corpus/2mc.json') as string[][],
  'mt': () => require('../corpus/mt.json') as string[][],
  'mc': () => require('../corpus/mc.json') as string[][],
  'lc': () => require('../corpus/lc.json') as string[][],
  'jo': () => require('../corpus/jo.json') as string[][],
  'at': () => require('../corpus/at.json') as string[][],
  'rm': () => require('../corpus/rm.json') as string[][],
  '1co': () => require('../corpus/1co.json') as string[][],
  '2co': () => require('../corpus/2co.json') as string[][],
  'gl': () => require('../corpus/gl.json') as string[][],
  'ef': () => require('../corpus/ef.json') as string[][],
  'fp': () => require('../corpus/fp.json') as string[][],
  'cl': () => require('../corpus/cl.json') as string[][],
  '1ts': () => require('../corpus/1ts.json') as string[][],
  '2ts': () => require('../corpus/2ts.json') as string[][],
  '1tm': () => require('../corpus/1tm.json') as string[][],
  '2tm': () => require('../corpus/2tm.json') as string[][],
  'tt': () => require('../corpus/tt.json') as string[][],
  'fm': () => require('../corpus/fm.json') as string[][],
  'hb': () => require('../corpus/hb.json') as string[][],
  'tg': () => require('../corpus/tg.json') as string[][],
  '1pe': () => require('../corpus/1pe.json') as string[][],
  '2pe': () => require('../corpus/2pe.json') as string[][],
  '1jo': () => require('../corpus/1jo.json') as string[][],
  '2jo': () => require('../corpus/2jo.json') as string[][],
  '3jo': () => require('../corpus/3jo.json') as string[][],
  'jd': () => require('../corpus/jd.json') as string[][],
  'ap': () => require('../corpus/ap.json') as string[][],
};

const bookCache = new Map<string, string[][]>();

/** Chapters for a book, required (and parsed) on first access, then kept. */
export function loadBookChapters(bookId: string): string[][] {
  const cached = bookCache.get(bookId);
  if (cached) return cached;
  const loader = bookLoaders[bookId];
  if (!loader) throw new Error(`Unknown book id: ${bookId}`);
  const chapters = loader();
  bookCache.set(bookId, chapters);
  return chapters;
}

export function loadChapterVerses(bookId: string, chapter: number): string[] {
  const chapters = loadBookChapters(bookId);
  const verses = chapters[chapter - 1];
  if (!verses) throw new Error(`Unknown chapter ${chapter} for book ${bookId}`);
  return verses;
}
